### ISSUE TITLE
💡 [REQUEST] - Add simple gitlab pipelines 

### ISSUE THREAD

**Issue by MateuszRostkowski** [binarapps/expo-ts-template#53]
### Summary

Add basic setup of gitlab pipelines:
- Install modules
- Run tests and linters on merge request

### Basic Example

```yml
stages:
  - dotenv
  - test

before_script:
  - yarn

## Running tests and linters
lint_test:
  image: node:16
  stage: test
  script:
    - echo "Running linters"
    - yarn lint
    - yarn tsc
    - echo "Running tests"
    - yarn test:final
    - echo "Linters and tests passed correctly"
  rules:

    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
```

### Drawbacks

We will need to maintain this script after making some changes.
